### ISSUE TITLE
[commits-by-year]: seq: unrecognized option '--since=2017-01-15 18:11:22 +0100'

### ISSUE THREAD

**Issue by vt-alt** [arzzen/git-quick-stats#172]
**To Reproduce**
1. Go to `   14) Git commits per year`
```
Git commits by year:

        year    sum
seq: unrecognized option '--since=2017-01-15 18:11:22 +0100'
Try 'seq --help' for more information.

```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version `master`

I have `date` set to `iso` in `~/.gitconfig` perhaps you should invoke `_since="--since=$(git log --reverse --format='%ad' | head -n1)"` requesting particular date format, like `--date=rfc`.

**Comment by tomice** [comment]
Confirmed bug when setting the `date = iso` in the `[log]` section of the `.gitconfig`. Root cause appears to be the `sed` commands in `commitsByYear()`. Main issue will be how to handle the `--date` format in git as it can now have:
`relative|relative-local|default|default-local|iso|iso-local|iso-strict|iso-strict-local|rfc|rfc-local|short|short-local|raw|raw-local`

Source: https://git-scm.com/docs/git-log#Documentation/git-log.txt---dateltformatgt

Will look into this and see what I can come up with.

**Comment by tomice** [comment]
Try my fork to see if this works for you. I tried setting `$_GIT_SINCE` to various different strings as a test with the following test cases:

UNIX: 1697375696
Default: Mon Oct 15 12:34:56 2023 +0000
Relative: 2 weeks ago
European: 15/10/2023
Single-Digit Day and Month: 1 Jan 2021
ISO: 2023-10-15 12:34:56 +0000
RFC: Mon, 15 Oct 2023 12:34:56 +0000
Short: 2023-10-15

**Comment by vt-alt** [comment]
If this is only for year stat why parse all possible date formats (and then convert it all to a year with `date`) instead of just requesting git to show expected date format with `--date`? Basically, `--date=rfc` (as suggested) have year fixed as the first number (and does not require any other changes).

**Comment by tomice** [comment]
`_GIT_SINCE` and `_GIT_UNTIL` are constructed in the sense that they can accept a wide variety of formats since they adhere to git's own `--since` and `--until`. These are our inputs for figuring out the date. git's own `--date` option only impacts the **output** format of the log or stuff like `git show`. We need to figure out a way to parse the dates ourselves to grab the year from the input portion (since and until), not the output portion, so I don't think `--date` wouldn't necessarily be useful in this case.

That said, I'm definitely open to alternative suggestions to solving this problem if you feel I'm off base on the solution to this, or if this solution isn't working out on other people's systems.
