### ISSUE TITLE
`showSignature = true` messes with stats

### ISSUE THREAD

**Issue by wendelscardua** [arzzen/git-quick-stats#52]
#### Expected behavior and actual behavior.

Expected: signature-related log text should be ignored by script
Actual: signature-related log text is parsed as if it was actual log text

#### Steps to reproduce the problem.

Enable on `~/.gitconfig`:
```
[log]
    showSignature = true
```

List contributors sorted by name, on a repository with signed commits:

`$ git quick-stats # and then select e.g. 7`

#### Notes

There exists some `git log` command line switch for overriding of this flag - I don't remember which one, but another git-related project used it to avoid this problem.

**Comment by tomice** [comment]
I believe this can be fixed by passing the `-c` flag to git and saying `log.showSignature=false` before the rest of the commands. For example, in `function contributors()`, we would change:
`git log --use-mailmap --no-merges --no-show-signature $_since $_until --format='%aN' $_pathspec | sort -u | cat -n`

to

`git -c log.showSignature=false log --use-mailmap --no-merges --no-show-signature $_since $_until --format='%aN' $_pathspec | sort -u | cat -n`

Unfortunately, I don't really have any repositories I work in that are signed, so I don't have a readily accessible way of testing to make sure this fix will work. If you have a moment, do you think you could test this and see if it is a possible fix? If it does work, I can create a pull request real quick to fix the issue. If it doesn't, I can try to investigate further.

**Comment by wendelscardua** [comment]
@tomice it works!

**Comment by arzzen** [comment]
Thanks @tomice and @wendelscardua, added in pull request #57
