### ISSUE TITLE
Maybe an easy enhancement to stats by user.

### ISSUE THREAD

**Issue by mjlefevre** [arzzen/git-quick-stats#73]
#### Possible Enhancement
When you run the number 1 option to get the git stats by user it would be nice if you could have the option to ignore the initial commit in some way. Often in older projects that have been moved from a previous source control system over to git, one user did the initial commit. Is it possible to ignore the first commit when running stats by user? Is it possible already and I just didn't see how to do it?

**Comment by tomice** [comment]
In git-quick-stats, we have a variable called _GIT_SINCE that can be used for this purpose. It functions like the --since option in git log and gives precision down to the second. You can change _GIT_SINCE to equal the date and time of the first commit so it can be ignored in your stats. Example:

`export _GIT_SINCE="2018-04-04T20:11:00"`

Then run git-quick-stats as normal. Is this something that could work for you?

**Comment by mjlefevre** [comment]
That should work for me. Does that affect anything else with normal git usage? or is the env variable unique to the stats script?

**Comment by tomice** [comment]
_GIT_SINCE is pretty unique. Here's a [quick search](https://github.com/search?q=%22_GIT_SINCE%22&type=Code) on GitHub that shows who else is using the var. It's mostly this program. Note that shell vars are case sensitive, so if there exists a _git_since, it will not interfere with _GIT_SINCE.

**Comment by drakegens** [comment]
Should this issue be closed?

**Comment by mjlefevre** [comment]
Yes. Thank you so much for the assistance.
