### ISSUE TITLE
Feature: show git stats for all (remote) branches

### ISSUE THREAD

**Issue by fransschreuder** [arzzen/git-quick-stats#83]
#### Expected behavior and actual behavior.
Right now there are some statistics on the current or a specific branch, I couldn't find a way to output per user commits for instance of all branches. Would be nice to have.

#### Steps to reproduce the problem.
-    
    
#### Specifications like the version of the project, operating system, or hardware.
-

**Comment by arzzen** [comment]
Hi @fransschreuder, after a long time ⌛ 

A new feature was implemented a couple of days ago,
if you want to include all branches logs, you can try using the following: `export _GIT_LOG_OPTIONS="--all"`.
Instead of `--all` you may want to use `--branches`, since `--all` also includes `refs/tags` and `refs/remotes`.

ps: more info about [git log --branches](https://git-scm.com/docs/git-log#Documentation/git-log.txt---branchesltpatterngt) or [git log --all](https://git-scm.com/docs/git-log#Documentation/git-log.txt---all)
