### ISSUE TITLE
could the env var _GIT_SINCE support the same formats as `git log`

### ISSUE THREAD

**Issue by fredericcogny** [arzzen/git-quick-stats#95]
`export _GIT_SINCE=<DateInIsoFormat>` works like a charm

However, with git log I can also use

```
git log --since="1 month ago"
git log --since="2 weeks 3 days ago"
```

and for stat generation I use it this way for instance

```
git log --author="Your Name Here" --since="1 month ago" --pretty=tformat: --numstat | awk '{ add += $1; subs += $2; loc += $1 - $2 } END { printf "added lines: %s, removed lines: %s, total lines: %s\n", add, subs, loc }' -
```

However when I do
```bash
export _GIT_SINCE="1 month ago" 
git quick-stats
> 2
> dev
```

I get the following

```
fatal: bad revision 'month'
```

Is there a way this could be do-able with quick-stats as well ? Would be nice.

**Comment by tomice** [comment]
This is happening because word splitting is occurring on all of the $_since and $_until variables. Originally, if we quoted $_since and $_until, the script would break due to "fatal revisions" if $_GIT_SINCE and $_GIT_UNTIL were not set and exported ahead of time, hence why they were (and still are) not quoted.

Playing around with some default configurations, I believe I have come up with a solution that'll work. Git log only allows people to go back as far as UNIX epoch time. I have logic I am working on where --since will be set to epoch time, and until will be set to the current date and time on the user's machine. This will be the default if the user does not set $_GIT_SINCE and $_GIT_UNTIL. If the user does set those, then those values will be respected, and word splitting will stop with the newly quoted variables.
